# Generated by Django 2.0.5 on 2018-05-02 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('yourscore', models.IntegerField()),
                ('opponentscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(help_text="Player's Name", max_length=200)),
                ('player_number', models.IntegerField()),
                ('imgfile', models.ImageField(blank=True, default='sample/noimage.png', null=True, upload_to='sample/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atbats', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=500)),
                ('league', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, default='teams/noteam.jpg', null=True, upload_to='teams/')),
                ('players', models.ManyToManyField(to='baseballapp.Player')),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='season_sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='baseballapp.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='yourteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='baseballapp.Team'),
        ),
    ]
