# Generated by Django 2.0.3 on 2018-04-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(max_length=200)),
                ('batting_avg', models.FloatField()),
                ('obp', models.FloatField(blank=True)),
                ('team', models.CharField(choices=[('Braves', 'Braves'), ('Tigers', 'Tigers'), ('Athletics', 'Athletics')], max_length=600)),
                ('player_number', models.IntegerField()),
            ],
        ),
    ]
