# Generated by Django 2.0.5 on 2018-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user_team',
            field=models.CharField(max_length=100),
        ),
    ]
