# Generated by Django 2.0.3 on 2018-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0002_auto_20180424_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.CharField(choices=[('AL', 'American League'), ('NL', 'National League'), ('MLB', 'All')], max_length=600),
        ),
    ]
