# Generated by Django 2.0.5 on 2018-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0002_auto_20180502_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user_team_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
