# Generated by Django 2.0.3 on 2018-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0003_auto_20180426_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hr',
        ),
    ]
