# Generated by Django 2.0.3 on 2018-04-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0004_remove_player_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='at_bats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_avg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='homeruns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='obp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plate_appearances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rbi',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='triples',
        ),
    ]
