# Generated by Django 2.0.3 on 2018-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0006_auto_20180426_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('Braves', 'Braves'), ('Tigers', 'Tigers')], max_length=600),
        ),
    ]
