# Generated by Django 2.0.4 on 2018-04-30 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0007_auto_20180426_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('yourscore', models.IntegerField()),
                ('opponentscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atbats', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=500)),
                ('league', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='playerimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='baseballapp.Player'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='season_sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Season'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='baseballapp.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='yourteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='baseballapp.Team'),
        ),
    ]
