# Generated by Django 2.0.4 on 2018-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0008_auto_20180429_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='sample'),
        ),
    ]
