# Generated by Django 2.0.4 on 2018-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0011_auto_20180430_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='imgfile',
            field=models.ImageField(blank=True, default='sample/noimage.png', null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.TextField(help_text="Player's Name", max_length=200),
        ),
    ]
