# Generated by Django 2.0.4 on 2018-05-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0013_auto_20180505_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
