# Generated by Django 2.0.4 on 2018-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0014_remove_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='baseballapp.Player'),
        ),
    ]
